version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:12.18.2

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - run: yarn build

      - aws-s3/sync:
          from: build
          to: "s3://userindexsearch/"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          
