export const userActionTypes = {
  SIGN_IN_START: 'SIGN_IN_START',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_OUT_FAIL: 'SIGN_OUT_FAIL',
};
